FROM python:3.14-slim

ARG SERVICE_NAME

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --require-hashes -r requirements.txt

COPY common /app/common
COPY ${SERVICE_NAME}/app.py /app/app.py

ENV PYTHONPATH=/app

CMD ["python", "app.py"]
