# nginx/nginx.conf
events {}

http {
  upstream kong_upstream {
    server kong:8000;
  }

  server {
    listen 80;

    location = /healthz {
      access_log off;
      return 200 'ok';
    }

    location / {
      proxy_pass http://kong_upstream;
    }
  }
}
